services:
  20079_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: 20079_backend
    restart: always
    volumes:
      - 20079_backend_static:/app/static
    environment:
      - PG_DATABASE_URL=postgresql+asyncpg://fastapi:fastapi@20079_db:5432/postgres
      - ENVIRONMENT=development
    entrypoint: ["/app/scripts/start-backend.dev.sh"]
    depends_on:
      20079_db:
        condition: service_healthy
        
  20079_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://20079-v1.deepsphere.one
    container_name: 20079_frontend
    restart: always
    depends_on:
      - 20079_backend
      - 20079_db

  20079_db:
    container_name: 20079_db
    image: postgres:16-alpine
    volumes:
      - 20079_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -U postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  20079_nginx:
    container_name: 20079_nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "20079:20079"
    depends_on:
      - 20079_backend
      - 20079_frontend
      - 20079_db

volumes:
  20079_db: {}
  20079_backend_static: {}