"""Initial migration

Revision ID: 00386817086e
Revises: 12869456edc5
Create Date: 2025-01-08 01:25:40.110665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00386817086e'
down_revision: Union[str, None] = '12869456edc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricecomparison',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('us_price', sa.Float(), nullable=False),
    sa.Column('international_price', sa.Float(), nullable=False),
    sa.Column('travel_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.uuid'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_pricecomparison_country_id'), 'pricecomparison', ['country_id'], unique=False)
    op.create_index(op.f('ix_pricecomparison_uuid'), 'pricecomparison', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricecomparison_uuid'), table_name='pricecomparison')
    op.drop_index(op.f('ix_pricecomparison_country_id'), table_name='pricecomparison')
    op.drop_table('pricecomparison')
    # ### end Alembic commands ###
