"""Initial migration

Revision ID: 12869456edc5
Revises: 875fe08bd886
Create Date: 2025-01-07 21:20:29.404126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12869456edc5'
down_revision: Union[str, None] = '875fe08bd886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certifications', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doctor_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_reviews', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_facility_location'), 'facility', ['location'], unique=False)
    op.create_index(op.f('ix_facility_name'), 'facility', ['name'], unique=False)
    op.create_index(op.f('ix_facility_uuid'), 'facility', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_uuid'), table_name='facility')
    op.drop_index(op.f('ix_facility_name'), table_name='facility')
    op.drop_index(op.f('ix_facility_location'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
