"""Initial migration

Revision ID: 16440e23c90d
Revises: 5ec1d40118a3
Create Date: 2025-01-06 18:50:04.718147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16440e23c90d'
down_revision: Union[str, None] = '5ec1d40118a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('us_price', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_procedure_category'), 'procedure', ['category'], unique=False)
    op.create_index(op.f('ix_procedure_name'), 'procedure', ['name'], unique=False)
    op.create_index(op.f('ix_procedure_uuid'), 'procedure', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedure_uuid'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_name'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_category'), table_name='procedure')
    op.drop_table('procedure')
    # ### end Alembic commands ###
