"""Initial migration

Revision ID: 53903a165fcf
Revises: 16440e23c90d
Create Date: 2025-01-06 19:11:02.068500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53903a165fcf'
down_revision: Union[str, None] = '16440e23c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_facility_location'), 'facility', ['location'], unique=False)
    op.create_index(op.f('ix_facility_name'), 'facility', ['name'], unique=False)
    op.create_index(op.f('ix_facility_uuid'), 'facility', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_uuid'), table_name='facility')
    op.drop_index(op.f('ix_facility_name'), table_name='facility')
    op.drop_index(op.f('ix_facility_location'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
